sudo: required
language: python
service:
 - docker
before_install:
 - sudo apt-get update
 - sudo apt-get install apache2 -y
script:
 - uname -r
 - ls
 - docker images
 #- sudo echo "hello" >> /var/www/html/gowtham.html
 - service apache2 start
 - curl http://localhost:80/

# gowthamshankar
